cat data.txt | grep 'ap*le'
cat data.txt | grep 'p.*le'
cat data.txt | grep '^ap*'
cat data.txt | grep 'a*$'
cat data.txt | grep 'c[ab]*n'
cat data.txt | grep 'p[a-z]*e'
cat data.txt | grep -E  'a+p+le'
cat data.txt | grep -E 'b[aeiou]+n[aeiou]+s*'
cat data.txt | grep -E '^[cp][aeiou]+[lr]+'
cat data.txt | grep -E '^grap?e+'
